$schema: https://azuremlschemas.azureedge.net/latest/pipelineComponent.schema.json
name: pdf_paddle_pipeline
version: '2'
type: pipeline
inputs:
  pdfs:
    type: uri_folder
outputs:
  results:
    type: uri_folder
    mode: rw_mount
jobs:
  parse:
    type: command
    component: ./paddle-command.yml
    inputs:
      models:
        type: custom_model
        path: azureml:pdf-paddle-models:1
        mode: download
      pdfs: ${{parent.inputs.pdfs}}
    outputs:
      results: ${{parent.outputs.results}}
    limits:
      timeout: 86400  # 24 hours for the whole batch.
