$schema: https://azuremlschemas.azureedge.net/latest/pipelineComponentBatchDeployment.schema.json
name: paddle-vl
endpoint_name: eppi-pdf-parsers-ccaesjm
type: pipeline
component: azureml:paddle_vl_pipeline:3
settings:
  default_compute: pdf-parsers-a100
  continue_on_step_failure: false
  force_rerun: true
