$schema: https://azuremlschemas.azureedge.net/latest/pipelineComponentBatchDeployment.schema.json
name: paddle
endpoint_name: eppi-pdf-parsers-ccaesjm
type: pipeline
component: azureml:pdf_paddle_pipeline:2
settings:
  default_compute: pdf-parsers-a100
  continue_on_step_failure: false
  force_rerun: true
